### ISSUE TITLE
Add the ability to correctly handle Virgo triggers

### ISSUE THREAD

**Issue by prbrady** [mina19/approval_processorMP#23]
@mina19 Please add a link to the diff between master and the virgoimplementation branch that you want to merge.

**Comment by mina19** [comment]
Hi Patrick -- here is the diff:
https://github.com/mina19/approval_processorMP/compare/virgoImplementation

**Comment by prbrady** [comment]
@mina19 This looks good. Thanks. Go ahead and merge it onto master and prepare the update to grinch.
